t_exception_propagation-x_declaration_parameter.adb:45:7: Error: declaration: declaration can propagate exceptions (declaration at level 3)
t_exception_propagation-x_declaration_parameter.adb:46:7: Error: declaration: declaration can propagate exceptions (declaration at level 1)
t_exception_propagation-x_declaration_parameter.adb:58:7: Error: declaration: declaration can propagate exceptions (declaration at level 3)
t_exception_propagation-x_declaration_parameter.adb:59:7: Error: declaration: declaration can propagate exceptions (declaration at level 2)
t_exception_propagation-x_declaration_parameter.adb:69:7: Error: declaration: declaration can propagate exceptions (declaration at level 3)
t_exception_propagation-x_declaration_parameter.adb:33:4: Error: Gen_Param: subprogram "Proc10" can propagate exceptions, used as call-back in instantiation at t_exception_propagation-x_declaration_parameter.adb:137:4
t_exception_propagation-x_declaration_parameter.adb:104:4: Error: Gen_Param: generic "Gen1" can propagate exceptions, instance "Inst1" at t_exception_propagation-x_declaration_parameter.adb:108:4 used as call-back in instantiation at t_exception_propagation-x_declaration_parameter.adb:138:4
t_exception_propagation-x_declaration_parameter.adb:140:4: Error: declaration: declaration can propagate exceptions (declaration at level 3)
t_exception_propagation-x_declaration_parameter.adb:33:4: Error: Param10: subprogram "Proc10" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:149:16
t_exception_propagation-x_declaration_parameter.adb:33:4: Error: Param11: subprogram "Proc10" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:155:16
t_exception_propagation-x_declaration_parameter.adb:40:4: Error: Param11: subprogram "Proc11" can propagate exceptions (declaration at level 1), used as call-back at t_exception_propagation-x_declaration_parameter.adb:156:16
t_exception_propagation-x_declaration_parameter.adb:33:4: Error: Param12: subprogram "Proc10" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:161:16
t_exception_propagation-x_declaration_parameter.adb:40:4: Error: Param12: subprogram "Proc11" can propagate exceptions (declaration at level 1), used as call-back at t_exception_propagation-x_declaration_parameter.adb:162:16
t_exception_propagation-x_declaration_parameter.adb:57:4: Error: Param12: subprogram "Proc12" can propagate exceptions (declaration at level 2), used as call-back at t_exception_propagation-x_declaration_parameter.adb:163:16
t_exception_propagation-x_declaration_parameter.adb:33:4: Error: Param13: subprogram "Proc10" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:167:16
t_exception_propagation-x_declaration_parameter.adb:40:4: Error: Param13: subprogram "Proc11" can propagate exceptions (declaration at level 3), used as call-back at t_exception_propagation-x_declaration_parameter.adb:168:16
t_exception_propagation-x_declaration_parameter.adb:57:4: Error: Param13: subprogram "Proc12" can propagate exceptions (declaration at level 3), used as call-back at t_exception_propagation-x_declaration_parameter.adb:169:16
t_exception_propagation-x_declaration_parameter.adb:68:4: Error: Param13: subprogram "Proc13" can propagate exceptions (declaration at level 3), used as call-back at t_exception_propagation-x_declaration_parameter.adb:170:16
t_exception_propagation-x_declaration_parameter.adb:77:4: Error: Param10: subprogram "Proc2" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:172:16
t_exception_propagation-x_declaration_parameter.adb:85:4: Error: Param10: subprogram "Proc3" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:173:16
t_exception_propagation-x_declaration_parameter.adb:104:4: Error: Param10: generic "Gen1" can propagate exceptions, instance "Inst1" at t_exception_propagation-x_declaration_parameter.adb:108:4 used as call-back at t_exception_propagation-x_declaration_parameter.adb:174:16
t_exception_propagation-x_declaration_parameter.adb:33:4: Error: Param4: subprogram "Proc10" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:176:9
t_exception_propagation-x_declaration_parameter.adb:33:4: Error: Param4: subprogram "Proc10" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:177:13
t_exception_propagation-x_declaration_parameter.adb:33:4: Error: Param2: subprogram "Proc10" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:179:11
t_exception_propagation-x_declaration_parameter.adb:33:4: Error: Param3: subprogram "Proc10" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:181:14
t_exception_propagation-x_declaration_parameter.adb:33:4: Error: Param100: subprogram "Proc10" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:184:20
t_exception_propagation-x_declaration_parameter.adb:33:4: Error: Param100: subprogram "Proc10" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:184:35
t_exception_propagation-x_declaration_parameter.adb:33:4: Error: Param100: subprogram "Proc10" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:185:20
t_exception_propagation-x_declaration_parameter.adb:33:4: Error: Param100: subprogram "Proc10" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:186:35
t_exception_propagation-x_interface.adb:6:4: Error: interf: subprogram "Proc_C1" can propagate exceptions, interfaced to C
t_exception_propagation-x_interface.adb:10:4: Error: interf: subprogram "Proc_C2" can propagate exceptions, interfaced to C
t_exception_propagation-x_interface.adb:20:4: Error: interf: subprogram "Proc_C3" can propagate exceptions, interfaced to C
t_exception_propagation-x_interface.adb:32:4: Error: interf: subprogram "F" can propagate exceptions, interfaced to C
t_exception_propagation-x_task.adb:4:4: Error: task: task "T1" can propagate exceptions
t_exception_propagation-x_task.adb:19:4: Error: task: task "T3" can propagate exceptions
t_exception_propagation-x_local_exception.adb:4:4: Found: local: No handler for local exception in enclosing body
t_exception_propagation-x_local_exception.adb:11:7: Found: local: handler can propagate local exception at t_exception_propagation-x_local_exception.adb:7:7
t_exception_propagation-x_local_exception.adb:16:7: Found: local: No handler for local exception in enclosing body
t_exception_propagation-x_local_exception.adb:23:7: Found: local: No handler for local exception in enclosing block
t_exception_propagation-x_local_exception.adb:36:7: Found: local: handler can propagate local exception at t_exception_propagation-x_local_exception.adb:32:7
t_exception_propagation-x_local_exception.adb:38:7: Found: local: handler can propagate local exception at t_exception_propagation-x_local_exception.adb:32:7
t_exception_propagation-x_local_exception.adb:50:7: Found: local: handler can propagate local exception at t_exception_propagation-x_local_exception.adb:45:7
