t_max_call_depth.adb:44:7: Error: MAX_CALL_DEPTH: Call to recursive entity
t_max_call_depth.adb:48:7: Error: MAX_CALL_DEPTH: Call to recursive entity
t_max_call_depth.adb:64:7: Found: MAX_CALL_DEPTH: Call has a depth of 2
t_max_call_depth.adb:75:10: Found: MAX_CALL_DEPTH: Call has a depth of 2
t_max_call_depth.adb:85:10: Found: MAX_CALL_DEPTH: Call has a depth of 2
t_max_call_depth.adb:109:19: Error: MAX_CALL_DEPTH: Call has a depth of 3
t_max_call_depth.adb:110:28: Error: MAX_CALL_DEPTH: Call has a depth of 3
t_max_call_depth.adb:111:38: Error: MAX_CALL_DEPTH: Call has a depth of 3
t_max_call_depth.adb:138:4: Found: MAX_CALL_DEPTH: Call has a depth of 2
t_max_call_depth.adb:139:4: Found: MAX_CALL_DEPTH: Call has a depth of 2
t_max_call_depth.adb:141:4: Error: MAX_CALL_DEPTH: Call to recursive entity
t_max_call_depth.adb:145:9: Error: MAX_CALL_DEPTH: Call has a depth of 3
t_max_call_depth.adb:146:12: Error: MAX_CALL_DEPTH: Call has a depth of 3
t_max_call_depth.adb:151:9: Error: MAX_CALL_DEPTH: Call has a depth of 3
t_max_call_depth.adb:152:9: Error: MAX_CALL_DEPTH: Call has a depth of 3
t_max_call_depth.adb:154:9: Error: MAX_CALL_DEPTH: Call has a depth of 3
t_max_call_depth.adb:158:4: Found: MAX_CALL_DEPTH: Call has a depth of at least 2

Counts summary:
Recursive calls: 3
