t_max_call_depth.adb:44:7: Error: MAX_CALL_DEPTH: Call to recursive entity
t_max_call_depth.adb:48:7: Error: MAX_CALL_DEPTH: Call to recursive entity
t_max_call_depth.adb:64:7: Found: MAX_CALL_DEPTH: Call has a depth of 2
t_max_call_depth.adb:75:10: Found: MAX_CALL_DEPTH: Call has a depth of 2
t_max_call_depth.adb:85:10: Found: MAX_CALL_DEPTH: Call has a depth of 2
t_max_call_depth.adb:103:19: Error: MAX_CALL_DEPTH: Call has a depth of 3
t_max_call_depth.adb:104:28: Error: MAX_CALL_DEPTH: Call has a depth of 3
t_max_call_depth.adb:105:38: Error: MAX_CALL_DEPTH: Call has a depth of 3
t_max_call_depth.adb:109:4: Found: MAX_CALL_DEPTH: Call has a depth of 2
t_max_call_depth.adb:110:4: Found: MAX_CALL_DEPTH: Call has a depth of 2
t_max_call_depth.adb:112:4: Error: MAX_CALL_DEPTH: Call to recursive entity
t_max_call_depth.adb:116:9: Error: MAX_CALL_DEPTH: Call has a depth of 3
t_max_call_depth.adb:117:12: Error: MAX_CALL_DEPTH: Call has a depth of 3
t_max_call_depth.adb:122:9: Error: MAX_CALL_DEPTH: Call has a depth of 3
t_max_call_depth.adb:123:9: Error: MAX_CALL_DEPTH: Call has a depth of 3

Counts summary:
Recursive calls: 3
